version: '3'
services:
  frontend:
    image: virta.azurecr.io/virta_frontend:latest
    restart: on-failure:5
    ports:
      - "80:80"

  backend:
    image: virta.azurecr.io/virta_backend:latest
    container_name: virta_backend
    restart: on-failure:5
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge
