version: '3.1'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: virta_postgres
    restart: on-failure:5
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_HOST}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    networks:
      - default

  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: virta_mongo
    restart: on-failure:5
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    ports:
      - ${MONGO_PORT_HOST}:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    networks:
      - default

  frontend:
    build:
      context: ./
      dockerfile: ./build/frontend/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    container_name: virta_frontend
    restart: on-failure:5
    # volumes:
    #   - ./Frontend:/app
    ports:
      - 80:80
      # - 4200:4200

  backend:
    build:
      context: ./
      dockerfile: ./build/asp/Dockerfile
    container_name: virta_backend
    restart: on-failure:5
    ports:
        - 8080:8080

volumes:
  postgres-data:
  mongo-data:

networks:
  default:
    driver: bridge
