version: '3.1'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: virta_postgres
    restart: on-failure:5
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_HOST}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: virta_pgadmin
    restart: on-failure:5
    env_file:
      - .env
    ports:
      - ${PGADMIN_PORT_HOST}:${PGADMIN_PORT}
    expose:
      - ${PGADMIN_PORT}
    networks:
      - default

  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: virta_mongo
    restart: on-failure:5
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    ports:
      - ${MONGO_PORT_HOST}:${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    networks:
      - default

  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_VERSION}
    container_name: virta_mongo-express
    restart: on-failure:5
    env_file:
      - .env
    ports:
      - ${MONGO_EXPRESS_PORT_HOST}:${MONGO_EXPRESS_PORT}
    networks:
      - default

  redis:
    image: redis:${REDIS_VERSION}
    container_name: virta_redis
    restart: on-failure:5
    env_file:
      - .env
    volumes:
      - redis-data:/data
    expose:
      - ${REDIS_PORT}
    networks:
      - default

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: virta_nginx
    restart: on-failure:30
    volumes:
    #   - ./build/nginx/:/etc/nginx/conf.d
      # - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app-data:/var/www/public
      - media-data:/var/www/public/pub/media
    env_file:
      - .env
    ports:
      - 81:${NGINX_BIND_PORT}
    #   - 443:443
    # expose:
    #   - 8080
    #   - 5043
    networks:
      - default

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: virta_rabbitmq
    restart: on-failure:30
    hostname: my-rabbit
    volumes:
      - ./build/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./build/rabbitmq/logs:/var/log/rabbitmq/log
    env_file:
      - .env
    ports:
      - ${RABBITMQ_PORT_HOST}:${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGMENT_PORT_HOST}:${RABBITMQ_MANAGMENT_PORT}
    expose:
      - ${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGMENT_PORT}
    networks:
      - default

  node:
    build:
      context: ./
      dockerfile: ./build/node/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    container_name: virta_node
    restart: on-failure:5
    volumes:
      - ./Node:/app
    ports:
      - ${NODE_PORT_HOST}:${NODE_PORT}

volumes:
  app-data:
  media-data:
  postgres-data:
  mongo-data:
  redis-data:

networks:
  default:
    driver: bridge
