version: '3.1'
services:
  postgres:
    image: postgres:alpine
    restart: on-failure:5
    environment:
      - POSTGRES_PASSWORD=toor
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    restart: on-failure:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./
      dockerfile: ./build/frontend/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    restart: on-failure:5
    volumes:
      - ./Frontend:/app
    ports:
      - "80:80"

  backend:
    build:
      context: ./
      dockerfile: ./build/asp/Dockerfile
    restart: on-failure:5
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"

volumes:
  postgres-data:
  mongo-data:
