name: Virta

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dotnet:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Api
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  angular:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend
    steps:
    - uses: actions/checkout@v1
    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 14.16.0
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Lint
      run: ./node_modules/.bin/eslint .
#     - name: Test
#       run: npm test -- --configuration=ci
#     - name: E2E
#       run: npm run e2e -- --configuration=ci
